// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.zzh.protocol;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InternalMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzh.protocol.InternalMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息唯一ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 timeStamp = 2;</code>
     */
    long getTimeStamp();

    /**
     * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
     */
    int getFromValue();
    /**
     * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
     */
    com.zzh.protocol.Internal.InternalMsg.Module getFrom();

    /**
     * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
     */
    int getDestValue();
    /**
     * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
     */
    com.zzh.protocol.Internal.InternalMsg.Module getDest();

    /**
     * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
     */
    int getMsgTypeValue();
    /**
     * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
     */
    com.zzh.protocol.Internal.InternalMsg.MsgType getMsgType();

    /**
     * <code>string body = 6;</code>
     */
    java.lang.String getBody();
    /**
     * <code>string body = 6;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code com.zzh.protocol.InternalMsg}
   */
  public  static final class InternalMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzh.protocol.InternalMsg)
      InternalMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InternalMsg.newBuilder() to construct.
    private InternalMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InternalMsg() {
      from_ = 0;
      dest_ = 0;
      msgType_ = 0;
      body_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              timeStamp_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              from_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              dest_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzh.protocol.Internal.internal_static_com_zzh_protocol_InternalMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzh.protocol.Internal.internal_static_com_zzh_protocol_InternalMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzh.protocol.Internal.InternalMsg.class, com.zzh.protocol.Internal.InternalMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code com.zzh.protocol.InternalMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GREET_REQUEST = 0;</code>
       */
      GREET_REQUEST(0),
      /**
       * <code>GREET_RESPONSE = 1;</code>
       */
      GREET_RESPONSE(1),
      /**
       * <code>HEART_REQUEST = 2;</code>
       */
      HEART_REQUEST(2),
      /**
       * <code>HEART_RESPONSE = 3;</code>
       */
      HEART_RESPONSE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GREET_REQUEST = 0;</code>
       */
      public static final int GREET_REQUEST_VALUE = 0;
      /**
       * <code>GREET_RESPONSE = 1;</code>
       */
      public static final int GREET_RESPONSE_VALUE = 1;
      /**
       * <code>HEART_REQUEST = 2;</code>
       */
      public static final int HEART_REQUEST_VALUE = 2;
      /**
       * <code>HEART_RESPONSE = 3;</code>
       */
      public static final int HEART_RESPONSE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return GREET_REQUEST;
          case 1: return GREET_RESPONSE;
          case 2: return HEART_REQUEST;
          case 3: return HEART_RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zzh.protocol.Internal.InternalMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.zzh.protocol.InternalMsg.MsgType)
    }

    /**
     * Protobuf enum {@code com.zzh.protocol.InternalMsg.Module}
     */
    public enum Module
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CLIENT = 0;</code>
       */
      CLIENT(0),
      /**
       * <code>SERVER = 1;</code>
       */
      SERVER(1),
      /**
       * <code>TRANSFER = 2;</code>
       */
      TRANSFER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CLIENT = 0;</code>
       */
      public static final int CLIENT_VALUE = 0;
      /**
       * <code>SERVER = 1;</code>
       */
      public static final int SERVER_VALUE = 1;
      /**
       * <code>TRANSFER = 2;</code>
       */
      public static final int TRANSFER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Module valueOf(int value) {
        return forNumber(value);
      }

      public static Module forNumber(int value) {
        switch (value) {
          case 0: return CLIENT;
          case 1: return SERVER;
          case 2: return TRANSFER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Module> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Module>() {
              public Module findValueByNumber(int number) {
                return Module.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zzh.protocol.Internal.InternalMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final Module[] VALUES = values();

      public static Module valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Module(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.zzh.protocol.InternalMsg.Module)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * 消息唯一ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timeStamp_;
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 timeStamp = 2;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int FROM_FIELD_NUMBER = 3;
    private int from_;
    /**
     * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
     */
    public int getFromValue() {
      return from_;
    }
    /**
     * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
     */
    public com.zzh.protocol.Internal.InternalMsg.Module getFrom() {
      @SuppressWarnings("deprecation")
      com.zzh.protocol.Internal.InternalMsg.Module result = com.zzh.protocol.Internal.InternalMsg.Module.valueOf(from_);
      return result == null ? com.zzh.protocol.Internal.InternalMsg.Module.UNRECOGNIZED : result;
    }

    public static final int DEST_FIELD_NUMBER = 4;
    private int dest_;
    /**
     * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
     */
    public int getDestValue() {
      return dest_;
    }
    /**
     * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
     */
    public com.zzh.protocol.Internal.InternalMsg.Module getDest() {
      @SuppressWarnings("deprecation")
      com.zzh.protocol.Internal.InternalMsg.Module result = com.zzh.protocol.Internal.InternalMsg.Module.valueOf(dest_);
      return result == null ? com.zzh.protocol.Internal.InternalMsg.Module.UNRECOGNIZED : result;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 5;
    private int msgType_;
    /**
     * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
     */
    public com.zzh.protocol.Internal.InternalMsg.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      com.zzh.protocol.Internal.InternalMsg.MsgType result = com.zzh.protocol.Internal.InternalMsg.MsgType.valueOf(msgType_);
      return result == null ? com.zzh.protocol.Internal.InternalMsg.MsgType.UNRECOGNIZED : result;
    }

    public static final int BODY_FIELD_NUMBER = 6;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 6;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (timeStamp_ != 0L) {
        output.writeInt64(2, timeStamp_);
      }
      if (from_ != com.zzh.protocol.Internal.InternalMsg.Module.CLIENT.getNumber()) {
        output.writeEnum(3, from_);
      }
      if (dest_ != com.zzh.protocol.Internal.InternalMsg.Module.CLIENT.getNumber()) {
        output.writeEnum(4, dest_);
      }
      if (msgType_ != com.zzh.protocol.Internal.InternalMsg.MsgType.GREET_REQUEST.getNumber()) {
        output.writeEnum(5, msgType_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timeStamp_);
      }
      if (from_ != com.zzh.protocol.Internal.InternalMsg.Module.CLIENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, from_);
      }
      if (dest_ != com.zzh.protocol.Internal.InternalMsg.Module.CLIENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, dest_);
      }
      if (msgType_ != com.zzh.protocol.Internal.InternalMsg.MsgType.GREET_REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, msgType_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzh.protocol.Internal.InternalMsg)) {
        return super.equals(obj);
      }
      com.zzh.protocol.Internal.InternalMsg other = (com.zzh.protocol.Internal.InternalMsg) obj;

      if (getId()
          != other.getId()) return false;
      if (getTimeStamp()
          != other.getTimeStamp()) return false;
      if (from_ != other.from_) return false;
      if (dest_ != other.dest_) return false;
      if (msgType_ != other.msgType_) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + from_;
      hash = (37 * hash) + DEST_FIELD_NUMBER;
      hash = (53 * hash) + dest_;
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzh.protocol.Internal.InternalMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protocol.Internal.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzh.protocol.Internal.InternalMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzh.protocol.InternalMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzh.protocol.InternalMsg)
        com.zzh.protocol.Internal.InternalMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzh.protocol.Internal.internal_static_com_zzh_protocol_InternalMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzh.protocol.Internal.internal_static_com_zzh_protocol_InternalMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzh.protocol.Internal.InternalMsg.class, com.zzh.protocol.Internal.InternalMsg.Builder.class);
      }

      // Construct using com.zzh.protocol.Internal.InternalMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        timeStamp_ = 0L;

        from_ = 0;

        dest_ = 0;

        msgType_ = 0;

        body_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzh.protocol.Internal.internal_static_com_zzh_protocol_InternalMsg_descriptor;
      }

      @java.lang.Override
      public com.zzh.protocol.Internal.InternalMsg getDefaultInstanceForType() {
        return com.zzh.protocol.Internal.InternalMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zzh.protocol.Internal.InternalMsg build() {
        com.zzh.protocol.Internal.InternalMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zzh.protocol.Internal.InternalMsg buildPartial() {
        com.zzh.protocol.Internal.InternalMsg result = new com.zzh.protocol.Internal.InternalMsg(this);
        result.id_ = id_;
        result.timeStamp_ = timeStamp_;
        result.from_ = from_;
        result.dest_ = dest_;
        result.msgType_ = msgType_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzh.protocol.Internal.InternalMsg) {
          return mergeFrom((com.zzh.protocol.Internal.InternalMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzh.protocol.Internal.InternalMsg other) {
        if (other == com.zzh.protocol.Internal.InternalMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.from_ != 0) {
          setFromValue(other.getFromValue());
        }
        if (other.dest_ != 0) {
          setDestValue(other.getDestValue());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzh.protocol.Internal.InternalMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzh.protocol.Internal.InternalMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * 消息唯一ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 消息唯一ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息唯一ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 timeStamp = 2;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 timeStamp = 2;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 timeStamp = 2;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private int from_ = 0;
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
       */
      public int getFromValue() {
        return from_;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
       */
      public Builder setFromValue(int value) {
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
       */
      public com.zzh.protocol.Internal.InternalMsg.Module getFrom() {
        @SuppressWarnings("deprecation")
        com.zzh.protocol.Internal.InternalMsg.Module result = com.zzh.protocol.Internal.InternalMsg.Module.valueOf(from_);
        return result == null ? com.zzh.protocol.Internal.InternalMsg.Module.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
       */
      public Builder setFrom(com.zzh.protocol.Internal.InternalMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        from_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module from = 3;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int dest_ = 0;
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
       */
      public int getDestValue() {
        return dest_;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
       */
      public Builder setDestValue(int value) {
        dest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
       */
      public com.zzh.protocol.Internal.InternalMsg.Module getDest() {
        @SuppressWarnings("deprecation")
        com.zzh.protocol.Internal.InternalMsg.Module result = com.zzh.protocol.Internal.InternalMsg.Module.valueOf(dest_);
        return result == null ? com.zzh.protocol.Internal.InternalMsg.Module.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
       */
      public Builder setDest(com.zzh.protocol.Internal.InternalMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dest_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.Module dest = 4;</code>
       */
      public Builder clearDest() {
        
        dest_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
       */
      public com.zzh.protocol.Internal.InternalMsg.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        com.zzh.protocol.Internal.InternalMsg.MsgType result = com.zzh.protocol.Internal.InternalMsg.MsgType.valueOf(msgType_);
        return result == null ? com.zzh.protocol.Internal.InternalMsg.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
       */
      public Builder setMsgType(com.zzh.protocol.Internal.InternalMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.zzh.protocol.InternalMsg.MsgType msgType = 5;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 6;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 6;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 6;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 6;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzh.protocol.InternalMsg)
    }

    // @@protoc_insertion_point(class_scope:com.zzh.protocol.InternalMsg)
    private static final com.zzh.protocol.Internal.InternalMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzh.protocol.Internal.InternalMsg();
    }

    public static com.zzh.protocol.Internal.InternalMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InternalMsg>
        PARSER = new com.google.protobuf.AbstractParser<InternalMsg>() {
      @java.lang.Override
      public InternalMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InternalMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zzh.protocol.Internal.InternalMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzh_protocol_InternalMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzh_protocol_InternalMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016internal.proto\022\020com.zzh.protocol\"\343\002\n\013I" +
      "nternalMsg\022\n\n\002id\030\001 \001(\003\022\021\n\ttimeStamp\030\002 \001(" +
      "\003\0222\n\004from\030\003 \001(\0162$.com.zzh.protocol.Inter" +
      "nalMsg.Module\0222\n\004dest\030\004 \001(\0162$.com.zzh.pr" +
      "otocol.InternalMsg.Module\0226\n\007msgType\030\005 \001" +
      "(\0162%.com.zzh.protocol.InternalMsg.MsgTyp" +
      "e\022\014\n\004body\030\006 \001(\t\"W\n\007MsgType\022\021\n\rGREET_REQU" +
      "EST\020\000\022\022\n\016GREET_RESPONSE\020\001\022\021\n\rHEART_REQUE" +
      "ST\020\002\022\022\n\016HEART_RESPONSE\020\003\".\n\006Module\022\n\n\006CL" +
      "IENT\020\000\022\n\n\006SERVER\020\001\022\014\n\010TRANSFER\020\002B\nB\010Inte" +
      "rnalb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zzh_protocol_InternalMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zzh_protocol_InternalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzh_protocol_InternalMsg_descriptor,
        new java.lang.String[] { "Id", "TimeStamp", "From", "Dest", "MsgType", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
