// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: single.proto

package com.zzh.protocol;

public final class Single {
  private Single() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SingleMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzh.protocol.SingleMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息唯一ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 timeStamp = 2;</code>
     */
    long getTimeStamp();

    /**
     * <pre>
     *    会话ID
     * </pre>
     *
     * <code>int64 sessionId = 3;</code>
     */
    long getSessionId();

    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    java.lang.String getFromId();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
     */
    int getFromModuleValue();
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
     */
    com.zzh.protocol.Single.SingleMsg.Module getFromModule();

    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    java.lang.String getDestId();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    com.google.protobuf.ByteString
        getDestIdBytes();

    /**
     * <pre>
     *接收者模块
     * </pre>
     *
     * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
     */
    int getDestModuleValue();
    /**
     * <pre>
     *接收者模块
     * </pre>
     *
     * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
     */
    com.zzh.protocol.Single.SingleMsg.Module getDestModule();

    /**
     * <pre>
     *  消息体 json
     * </pre>
     *
     * <code>string body = 8;</code>
     */
    java.lang.String getBody();
    /**
     * <pre>
     *  消息体 json
     * </pre>
     *
     * <code>string body = 8;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code com.zzh.protocol.SingleMsg}
   */
  public  static final class SingleMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzh.protocol.SingleMsg)
      SingleMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SingleMsg.newBuilder() to construct.
    private SingleMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SingleMsg() {
      fromId_ = "";
      fromModule_ = 0;
      destId_ = "";
      destModule_ = 0;
      body_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SingleMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              timeStamp_ = input.readInt64();
              break;
            }
            case 24: {

              sessionId_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fromId_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              fromModule_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              destId_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              destModule_ = rawValue;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzh.protocol.Single.internal_static_com_zzh_protocol_SingleMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzh.protocol.Single.internal_static_com_zzh_protocol_SingleMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzh.protocol.Single.SingleMsg.class, com.zzh.protocol.Single.SingleMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code com.zzh.protocol.SingleMsg.Module}
     */
    public enum Module
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CLIENT = 0;</code>
       */
      CLIENT(0),
      /**
       * <code>SERVER = 1;</code>
       */
      SERVER(1),
      /**
       * <code>TRANSFER = 2;</code>
       */
      TRANSFER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CLIENT = 0;</code>
       */
      public static final int CLIENT_VALUE = 0;
      /**
       * <code>SERVER = 1;</code>
       */
      public static final int SERVER_VALUE = 1;
      /**
       * <code>TRANSFER = 2;</code>
       */
      public static final int TRANSFER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Module valueOf(int value) {
        return forNumber(value);
      }

      public static Module forNumber(int value) {
        switch (value) {
          case 0: return CLIENT;
          case 1: return SERVER;
          case 2: return TRANSFER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Module> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Module>() {
              public Module findValueByNumber(int number) {
                return Module.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zzh.protocol.Single.SingleMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Module[] VALUES = values();

      public static Module valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Module(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.zzh.protocol.SingleMsg.Module)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * 消息唯一ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timeStamp_;
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 timeStamp = 2;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionId_;
    /**
     * <pre>
     *    会话ID
     * </pre>
     *
     * <code>int64 sessionId = 3;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int FROMID_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromId_;
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMMODULE_FIELD_NUMBER = 5;
    private int fromModule_;
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
     */
    public int getFromModuleValue() {
      return fromModule_;
    }
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
     */
    public com.zzh.protocol.Single.SingleMsg.Module getFromModule() {
      @SuppressWarnings("deprecation")
      com.zzh.protocol.Single.SingleMsg.Module result = com.zzh.protocol.Single.SingleMsg.Module.valueOf(fromModule_);
      return result == null ? com.zzh.protocol.Single.SingleMsg.Module.UNRECOGNIZED : result;
    }

    public static final int DESTID_FIELD_NUMBER = 6;
    private volatile java.lang.Object destId_;
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    public java.lang.String getDestId() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTMODULE_FIELD_NUMBER = 7;
    private int destModule_;
    /**
     * <pre>
     *接收者模块
     * </pre>
     *
     * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
     */
    public int getDestModuleValue() {
      return destModule_;
    }
    /**
     * <pre>
     *接收者模块
     * </pre>
     *
     * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
     */
    public com.zzh.protocol.Single.SingleMsg.Module getDestModule() {
      @SuppressWarnings("deprecation")
      com.zzh.protocol.Single.SingleMsg.Module result = com.zzh.protocol.Single.SingleMsg.Module.valueOf(destModule_);
      return result == null ? com.zzh.protocol.Single.SingleMsg.Module.UNRECOGNIZED : result;
    }

    public static final int BODY_FIELD_NUMBER = 8;
    private volatile java.lang.Object body_;
    /**
     * <pre>
     *  消息体 json
     * </pre>
     *
     * <code>string body = 8;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  消息体 json
     * </pre>
     *
     * <code>string body = 8;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (timeStamp_ != 0L) {
        output.writeInt64(2, timeStamp_);
      }
      if (sessionId_ != 0L) {
        output.writeInt64(3, sessionId_);
      }
      if (!getFromIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromId_);
      }
      if (fromModule_ != com.zzh.protocol.Single.SingleMsg.Module.CLIENT.getNumber()) {
        output.writeEnum(5, fromModule_);
      }
      if (!getDestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, destId_);
      }
      if (destModule_ != com.zzh.protocol.Single.SingleMsg.Module.CLIENT.getNumber()) {
        output.writeEnum(7, destModule_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timeStamp_);
      }
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sessionId_);
      }
      if (!getFromIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromId_);
      }
      if (fromModule_ != com.zzh.protocol.Single.SingleMsg.Module.CLIENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, fromModule_);
      }
      if (!getDestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, destId_);
      }
      if (destModule_ != com.zzh.protocol.Single.SingleMsg.Module.CLIENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, destModule_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzh.protocol.Single.SingleMsg)) {
        return super.equals(obj);
      }
      com.zzh.protocol.Single.SingleMsg other = (com.zzh.protocol.Single.SingleMsg) obj;

      if (getId()
          != other.getId()) return false;
      if (getTimeStamp()
          != other.getTimeStamp()) return false;
      if (getSessionId()
          != other.getSessionId()) return false;
      if (!getFromId()
          .equals(other.getFromId())) return false;
      if (fromModule_ != other.fromModule_) return false;
      if (!getDestId()
          .equals(other.getDestId())) return false;
      if (destModule_ != other.destModule_) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
      hash = (37 * hash) + FROMMODULE_FIELD_NUMBER;
      hash = (53 * hash) + fromModule_;
      hash = (37 * hash) + DESTID_FIELD_NUMBER;
      hash = (53 * hash) + getDestId().hashCode();
      hash = (37 * hash) + DESTMODULE_FIELD_NUMBER;
      hash = (53 * hash) + destModule_;
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzh.protocol.Single.SingleMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protocol.Single.SingleMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzh.protocol.Single.SingleMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protocol.Single.SingleMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzh.protocol.Single.SingleMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzh.protocol.SingleMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzh.protocol.SingleMsg)
        com.zzh.protocol.Single.SingleMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzh.protocol.Single.internal_static_com_zzh_protocol_SingleMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzh.protocol.Single.internal_static_com_zzh_protocol_SingleMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzh.protocol.Single.SingleMsg.class, com.zzh.protocol.Single.SingleMsg.Builder.class);
      }

      // Construct using com.zzh.protocol.Single.SingleMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        timeStamp_ = 0L;

        sessionId_ = 0L;

        fromId_ = "";

        fromModule_ = 0;

        destId_ = "";

        destModule_ = 0;

        body_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzh.protocol.Single.internal_static_com_zzh_protocol_SingleMsg_descriptor;
      }

      @java.lang.Override
      public com.zzh.protocol.Single.SingleMsg getDefaultInstanceForType() {
        return com.zzh.protocol.Single.SingleMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zzh.protocol.Single.SingleMsg build() {
        com.zzh.protocol.Single.SingleMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zzh.protocol.Single.SingleMsg buildPartial() {
        com.zzh.protocol.Single.SingleMsg result = new com.zzh.protocol.Single.SingleMsg(this);
        result.id_ = id_;
        result.timeStamp_ = timeStamp_;
        result.sessionId_ = sessionId_;
        result.fromId_ = fromId_;
        result.fromModule_ = fromModule_;
        result.destId_ = destId_;
        result.destModule_ = destModule_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzh.protocol.Single.SingleMsg) {
          return mergeFrom((com.zzh.protocol.Single.SingleMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzh.protocol.Single.SingleMsg other) {
        if (other == com.zzh.protocol.Single.SingleMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (!other.getFromId().isEmpty()) {
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.fromModule_ != 0) {
          setFromModuleValue(other.getFromModuleValue());
        }
        if (!other.getDestId().isEmpty()) {
          destId_ = other.destId_;
          onChanged();
        }
        if (other.destModule_ != 0) {
          setDestModuleValue(other.getDestModuleValue());
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzh.protocol.Single.SingleMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzh.protocol.Single.SingleMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * 消息唯一ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 消息唯一ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息唯一ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 timeStamp = 2;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 timeStamp = 2;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 timeStamp = 2;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <pre>
       *    会话ID
       * </pre>
       *
       * <code>int64 sessionId = 3;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <pre>
       *    会话ID
       * </pre>
       *
       * <code>int64 sessionId = 3;</code>
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    会话ID
       * </pre>
       *
       * <code>int64 sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fromId_ = "";
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder clearFromId() {
        
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromId_ = value;
        onChanged();
        return this;
      }

      private int fromModule_ = 0;
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
       */
      public int getFromModuleValue() {
        return fromModule_;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
       */
      public Builder setFromModuleValue(int value) {
        fromModule_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
       */
      public com.zzh.protocol.Single.SingleMsg.Module getFromModule() {
        @SuppressWarnings("deprecation")
        com.zzh.protocol.Single.SingleMsg.Module result = com.zzh.protocol.Single.SingleMsg.Module.valueOf(fromModule_);
        return result == null ? com.zzh.protocol.Single.SingleMsg.Module.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
       */
      public Builder setFromModule(com.zzh.protocol.Single.SingleMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fromModule_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module fromModule = 5;</code>
       */
      public Builder clearFromModule() {
        
        fromModule_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object destId_ = "";
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public java.lang.String getDestId() {
        java.lang.Object ref = destId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDestIdBytes() {
        java.lang.Object ref = destId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder setDestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder clearDestId() {
        
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder setDestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destId_ = value;
        onChanged();
        return this;
      }

      private int destModule_ = 0;
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
       */
      public int getDestModuleValue() {
        return destModule_;
      }
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
       */
      public Builder setDestModuleValue(int value) {
        destModule_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
       */
      public com.zzh.protocol.Single.SingleMsg.Module getDestModule() {
        @SuppressWarnings("deprecation")
        com.zzh.protocol.Single.SingleMsg.Module result = com.zzh.protocol.Single.SingleMsg.Module.valueOf(destModule_);
        return result == null ? com.zzh.protocol.Single.SingleMsg.Module.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
       */
      public Builder setDestModule(com.zzh.protocol.Single.SingleMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        destModule_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protocol.SingleMsg.Module destModule = 7;</code>
       */
      public Builder clearDestModule() {
        
        destModule_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <pre>
       *  消息体 json
       * </pre>
       *
       * <code>string body = 8;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  消息体 json
       * </pre>
       *
       * <code>string body = 8;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  消息体 json
       * </pre>
       *
       * <code>string body = 8;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  消息体 json
       * </pre>
       *
       * <code>string body = 8;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  消息体 json
       * </pre>
       *
       * <code>string body = 8;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzh.protocol.SingleMsg)
    }

    // @@protoc_insertion_point(class_scope:com.zzh.protocol.SingleMsg)
    private static final com.zzh.protocol.Single.SingleMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzh.protocol.Single.SingleMsg();
    }

    public static com.zzh.protocol.Single.SingleMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SingleMsg>
        PARSER = new com.google.protobuf.AbstractParser<SingleMsg>() {
      @java.lang.Override
      public SingleMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SingleMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SingleMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SingleMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zzh.protocol.Single.SingleMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzh_protocol_SingleMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzh_protocol_SingleMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014single.proto\022\020com.zzh.protocol\"\213\002\n\tSin" +
      "gleMsg\022\n\n\002id\030\001 \001(\003\022\021\n\ttimeStamp\030\002 \001(\003\022\021\n" +
      "\tsessionId\030\003 \001(\003\022\016\n\006fromId\030\004 \001(\t\0226\n\nfrom" +
      "Module\030\005 \001(\0162\".com.zzh.protocol.SingleMs" +
      "g.Module\022\016\n\006destId\030\006 \001(\t\0226\n\ndestModule\030\007" +
      " \001(\0162\".com.zzh.protocol.SingleMsg.Module" +
      "\022\014\n\004body\030\010 \001(\t\".\n\006Module\022\n\n\006CLIENT\020\000\022\n\n\006" +
      "SERVER\020\001\022\014\n\010TRANSFER\020\002B\010B\006Singleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zzh_protocol_SingleMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zzh_protocol_SingleMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzh_protocol_SingleMsg_descriptor,
        new java.lang.String[] { "Id", "TimeStamp", "SessionId", "FromId", "FromModule", "DestId", "DestModule", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
