// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.zzh.protobuf;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.zzh.protobuf.Module}
   */
  public enum Module
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLIENT = 0;</code>
     */
    CLIENT(0),
    /**
     * <code>SERVER = 1;</code>
     */
    SERVER(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLIENT = 0;</code>
     */
    public static final int CLIENT_VALUE = 0;
    /**
     * <code>SERVER = 1;</code>
     */
    public static final int SERVER_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Module valueOf(int value) {
      return forNumber(value);
    }

    public static Module forNumber(int value) {
      switch (value) {
        case 0: return CLIENT;
        case 1: return SERVER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Module>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Module> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Module>() {
            public Module findValueByNumber(int number) {
              return Module.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zzh.protobuf.Msg.getDescriptor().getEnumTypes().get(0);
    }

    private static final Module[] VALUES = values();

    public static Module valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Module(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zzh.protobuf.Module)
  }

  /**
   * Protobuf enum {@code com.zzh.protobuf.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *私聊消息
     * </pre>
     *
     * <code>SINGLE = 0;</code>
     */
    SINGLE(0),
    /**
     * <pre>
     *群聊消息
     * </pre>
     *
     * <code>GROUP = 2;</code>
     */
    GROUP(2),
    /**
     * <pre>
     *登录问候
     * </pre>
     *
     * <code>GREET = 3;</code>
     */
    GREET(3),
    /**
     * <pre>
     *ack
     * </pre>
     *
     * <code>ACK = 4;</code>
     */
    ACK(4),
    /**
     * <pre>
     *错误
     * </pre>
     *
     * <code>ERROR = 5;</code>
     */
    ERROR(5),
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HEART = 6;</code>
     */
    HEART(6),
    /**
     * <pre>
     *下线
     * </pre>
     *
     * <code>OFFLINE = 7;</code>
     */
    OFFLINE(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *私聊消息
     * </pre>
     *
     * <code>SINGLE = 0;</code>
     */
    public static final int SINGLE_VALUE = 0;
    /**
     * <pre>
     *群聊消息
     * </pre>
     *
     * <code>GROUP = 2;</code>
     */
    public static final int GROUP_VALUE = 2;
    /**
     * <pre>
     *登录问候
     * </pre>
     *
     * <code>GREET = 3;</code>
     */
    public static final int GREET_VALUE = 3;
    /**
     * <pre>
     *ack
     * </pre>
     *
     * <code>ACK = 4;</code>
     */
    public static final int ACK_VALUE = 4;
    /**
     * <pre>
     *错误
     * </pre>
     *
     * <code>ERROR = 5;</code>
     */
    public static final int ERROR_VALUE = 5;
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HEART = 6;</code>
     */
    public static final int HEART_VALUE = 6;
    /**
     * <pre>
     *下线
     * </pre>
     *
     * <code>OFFLINE = 7;</code>
     */
    public static final int OFFLINE_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return SINGLE;
        case 2: return GROUP;
        case 3: return GREET;
        case 4: return ACK;
        case 5: return ERROR;
        case 6: return HEART;
        case 7: return OFFLINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zzh.protobuf.Msg.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zzh.protobuf.MsgType)
  }

  public interface ProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzh.protobuf.Protocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息头
     * </pre>
     *
     * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
     */
    boolean hasMsgHead();
    /**
     * <pre>
     *消息头
     * </pre>
     *
     * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
     */
    com.zzh.protobuf.Msg.Head getMsgHead();
    /**
     * <pre>
     *消息头
     * </pre>
     *
     * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
     */
    com.zzh.protobuf.Msg.HeadOrBuilder getMsgHeadOrBuilder();

    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 2;</code>
     */
    java.lang.String getMsgBody();
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBodyBytes();

    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string addition = 3;</code>
     */
    java.lang.String getAddition();
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string addition = 3;</code>
     */
    com.google.protobuf.ByteString
        getAdditionBytes();
  }
  /**
   * Protobuf type {@code com.zzh.protobuf.Protocol}
   */
  public  static final class Protocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzh.protobuf.Protocol)
      ProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Protocol.newBuilder() to construct.
    private Protocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Protocol() {
      msgBody_ = "";
      addition_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Protocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.zzh.protobuf.Msg.Head.Builder subBuilder = null;
              if (msgHead_ != null) {
                subBuilder = msgHead_.toBuilder();
              }
              msgHead_ = input.readMessage(com.zzh.protobuf.Msg.Head.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msgHead_);
                msgHead_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msgBody_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              addition_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Protocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Protocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzh.protobuf.Msg.Protocol.class, com.zzh.protobuf.Msg.Protocol.Builder.class);
    }

    public static final int MSGHEAD_FIELD_NUMBER = 1;
    private com.zzh.protobuf.Msg.Head msgHead_;
    /**
     * <pre>
     *消息头
     * </pre>
     *
     * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
     */
    public boolean hasMsgHead() {
      return msgHead_ != null;
    }
    /**
     * <pre>
     *消息头
     * </pre>
     *
     * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
     */
    public com.zzh.protobuf.Msg.Head getMsgHead() {
      return msgHead_ == null ? com.zzh.protobuf.Msg.Head.getDefaultInstance() : msgHead_;
    }
    /**
     * <pre>
     *消息头
     * </pre>
     *
     * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
     */
    public com.zzh.protobuf.Msg.HeadOrBuilder getMsgHeadOrBuilder() {
      return getMsgHead();
    }

    public static final int MSGBODY_FIELD_NUMBER = 2;
    private volatile java.lang.Object msgBody_;
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 2;</code>
     */
    public java.lang.String getMsgBody() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgBody_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDITION_FIELD_NUMBER = 3;
    private volatile java.lang.Object addition_;
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string addition = 3;</code>
     */
    public java.lang.String getAddition() {
      java.lang.Object ref = addition_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addition_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string addition = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAdditionBytes() {
      java.lang.Object ref = addition_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgHead_ != null) {
        output.writeMessage(1, getMsgHead());
      }
      if (!getMsgBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgBody_);
      }
      if (!getAdditionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, addition_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgHead_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsgHead());
      }
      if (!getMsgBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgBody_);
      }
      if (!getAdditionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, addition_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzh.protobuf.Msg.Protocol)) {
        return super.equals(obj);
      }
      com.zzh.protobuf.Msg.Protocol other = (com.zzh.protobuf.Msg.Protocol) obj;

      if (hasMsgHead() != other.hasMsgHead()) return false;
      if (hasMsgHead()) {
        if (!getMsgHead()
            .equals(other.getMsgHead())) return false;
      }
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
      if (!getAddition()
          .equals(other.getAddition())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgHead()) {
        hash = (37 * hash) + MSGHEAD_FIELD_NUMBER;
        hash = (53 * hash) + getMsgHead().hashCode();
      }
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      hash = (37 * hash) + ADDITION_FIELD_NUMBER;
      hash = (53 * hash) + getAddition().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzh.protobuf.Msg.Protocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Protocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Msg.Protocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Msg.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzh.protobuf.Msg.Protocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzh.protobuf.Protocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzh.protobuf.Protocol)
        com.zzh.protobuf.Msg.ProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Protocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Protocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzh.protobuf.Msg.Protocol.class, com.zzh.protobuf.Msg.Protocol.Builder.class);
      }

      // Construct using com.zzh.protobuf.Msg.Protocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (msgHeadBuilder_ == null) {
          msgHead_ = null;
        } else {
          msgHead_ = null;
          msgHeadBuilder_ = null;
        }
        msgBody_ = "";

        addition_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Protocol_descriptor;
      }

      @java.lang.Override
      public com.zzh.protobuf.Msg.Protocol getDefaultInstanceForType() {
        return com.zzh.protobuf.Msg.Protocol.getDefaultInstance();
      }

      @java.lang.Override
      public com.zzh.protobuf.Msg.Protocol build() {
        com.zzh.protobuf.Msg.Protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zzh.protobuf.Msg.Protocol buildPartial() {
        com.zzh.protobuf.Msg.Protocol result = new com.zzh.protobuf.Msg.Protocol(this);
        if (msgHeadBuilder_ == null) {
          result.msgHead_ = msgHead_;
        } else {
          result.msgHead_ = msgHeadBuilder_.build();
        }
        result.msgBody_ = msgBody_;
        result.addition_ = addition_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzh.protobuf.Msg.Protocol) {
          return mergeFrom((com.zzh.protobuf.Msg.Protocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzh.protobuf.Msg.Protocol other) {
        if (other == com.zzh.protobuf.Msg.Protocol.getDefaultInstance()) return this;
        if (other.hasMsgHead()) {
          mergeMsgHead(other.getMsgHead());
        }
        if (!other.getMsgBody().isEmpty()) {
          msgBody_ = other.msgBody_;
          onChanged();
        }
        if (!other.getAddition().isEmpty()) {
          addition_ = other.addition_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzh.protobuf.Msg.Protocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzh.protobuf.Msg.Protocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.zzh.protobuf.Msg.Head msgHead_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zzh.protobuf.Msg.Head, com.zzh.protobuf.Msg.Head.Builder, com.zzh.protobuf.Msg.HeadOrBuilder> msgHeadBuilder_;
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      public boolean hasMsgHead() {
        return msgHeadBuilder_ != null || msgHead_ != null;
      }
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      public com.zzh.protobuf.Msg.Head getMsgHead() {
        if (msgHeadBuilder_ == null) {
          return msgHead_ == null ? com.zzh.protobuf.Msg.Head.getDefaultInstance() : msgHead_;
        } else {
          return msgHeadBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      public Builder setMsgHead(com.zzh.protobuf.Msg.Head value) {
        if (msgHeadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgHead_ = value;
          onChanged();
        } else {
          msgHeadBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      public Builder setMsgHead(
          com.zzh.protobuf.Msg.Head.Builder builderForValue) {
        if (msgHeadBuilder_ == null) {
          msgHead_ = builderForValue.build();
          onChanged();
        } else {
          msgHeadBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      public Builder mergeMsgHead(com.zzh.protobuf.Msg.Head value) {
        if (msgHeadBuilder_ == null) {
          if (msgHead_ != null) {
            msgHead_ =
              com.zzh.protobuf.Msg.Head.newBuilder(msgHead_).mergeFrom(value).buildPartial();
          } else {
            msgHead_ = value;
          }
          onChanged();
        } else {
          msgHeadBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      public Builder clearMsgHead() {
        if (msgHeadBuilder_ == null) {
          msgHead_ = null;
          onChanged();
        } else {
          msgHead_ = null;
          msgHeadBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      public com.zzh.protobuf.Msg.Head.Builder getMsgHeadBuilder() {
        
        onChanged();
        return getMsgHeadFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      public com.zzh.protobuf.Msg.HeadOrBuilder getMsgHeadOrBuilder() {
        if (msgHeadBuilder_ != null) {
          return msgHeadBuilder_.getMessageOrBuilder();
        } else {
          return msgHead_ == null ?
              com.zzh.protobuf.Msg.Head.getDefaultInstance() : msgHead_;
        }
      }
      /**
       * <pre>
       *消息头
       * </pre>
       *
       * <code>.com.zzh.protobuf.Head msgHead = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zzh.protobuf.Msg.Head, com.zzh.protobuf.Msg.Head.Builder, com.zzh.protobuf.Msg.HeadOrBuilder> 
          getMsgHeadFieldBuilder() {
        if (msgHeadBuilder_ == null) {
          msgHeadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zzh.protobuf.Msg.Head, com.zzh.protobuf.Msg.Head.Builder, com.zzh.protobuf.Msg.HeadOrBuilder>(
                  getMsgHead(),
                  getParentForChildren(),
                  isClean());
          msgHead_ = null;
        }
        return msgHeadBuilder_;
      }

      private java.lang.Object msgBody_ = "";
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 2;</code>
       */
      public java.lang.String getMsgBody() {
        java.lang.Object ref = msgBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBodyBytes() {
        java.lang.Object ref = msgBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 2;</code>
       */
      public Builder setMsgBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 2;</code>
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 2;</code>
       */
      public Builder setMsgBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgBody_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object addition_ = "";
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 3;</code>
       */
      public java.lang.String getAddition() {
        java.lang.Object ref = addition_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addition_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAdditionBytes() {
        java.lang.Object ref = addition_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addition_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 3;</code>
       */
      public Builder setAddition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addition_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 3;</code>
       */
      public Builder clearAddition() {
        
        addition_ = getDefaultInstance().getAddition();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 3;</code>
       */
      public Builder setAdditionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addition_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzh.protobuf.Protocol)
    }

    // @@protoc_insertion_point(class_scope:com.zzh.protobuf.Protocol)
    private static final com.zzh.protobuf.Msg.Protocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzh.protobuf.Msg.Protocol();
    }

    public static com.zzh.protobuf.Msg.Protocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Protocol>
        PARSER = new com.google.protobuf.AbstractParser<Protocol>() {
      @java.lang.Override
      public Protocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Protocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Protocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Protocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zzh.protobuf.Msg.Protocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzh.protobuf.Head)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     *消息唯一id
     * </pre>
     *
     * <code>int64 msgId = 2;</code>
     */
    long getMsgId();

    /**
     * <pre>
     *发送者module
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
     */
    int getFromModuleValue();
    /**
     * <pre>
     *发送者module
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
     */
    com.zzh.protobuf.Msg.Module getFromModule();

    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    java.lang.String getFromId();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <pre>
     *接收者module
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module destModule = 5;</code>
     */
    int getDestModuleValue();
    /**
     * <pre>
     *接收者module
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module destModule = 5;</code>
     */
    com.zzh.protobuf.Msg.Module getDestModule();

    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    java.lang.String getDestId();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    com.google.protobuf.ByteString
        getDestIdBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 timeStamp = 7;</code>
     */
    long getTimeStamp();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
     */
    int getMsgTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
     */
    com.zzh.protobuf.Msg.MsgType getMsgType();
  }
  /**
   * Protobuf type {@code com.zzh.protobuf.Head}
   */
  public  static final class Head extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzh.protobuf.Head)
      HeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Head.newBuilder() to construct.
    private Head(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Head() {
      fromModule_ = 0;
      fromId_ = "";
      destModule_ = 0;
      destId_ = "";
      msgType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Head(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 16: {

              msgId_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              fromModule_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fromId_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              destModule_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              destId_ = s;
              break;
            }
            case 56: {

              timeStamp_ = input.readInt64();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Head_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Head_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzh.protobuf.Msg.Head.class, com.zzh.protobuf.Msg.Head.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int MSGID_FIELD_NUMBER = 2;
    private long msgId_;
    /**
     * <pre>
     *消息唯一id
     * </pre>
     *
     * <code>int64 msgId = 2;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int FROMMODULE_FIELD_NUMBER = 3;
    private int fromModule_;
    /**
     * <pre>
     *发送者module
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
     */
    public int getFromModuleValue() {
      return fromModule_;
    }
    /**
     * <pre>
     *发送者module
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
     */
    public com.zzh.protobuf.Msg.Module getFromModule() {
      @SuppressWarnings("deprecation")
      com.zzh.protobuf.Msg.Module result = com.zzh.protobuf.Msg.Module.valueOf(fromModule_);
      return result == null ? com.zzh.protobuf.Msg.Module.UNRECOGNIZED : result;
    }

    public static final int FROMID_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromId_;
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTMODULE_FIELD_NUMBER = 5;
    private int destModule_;
    /**
     * <pre>
     *接收者module
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module destModule = 5;</code>
     */
    public int getDestModuleValue() {
      return destModule_;
    }
    /**
     * <pre>
     *接收者module
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module destModule = 5;</code>
     */
    public com.zzh.protobuf.Msg.Module getDestModule() {
      @SuppressWarnings("deprecation")
      com.zzh.protobuf.Msg.Module result = com.zzh.protobuf.Msg.Module.valueOf(destModule_);
      return result == null ? com.zzh.protobuf.Msg.Module.UNRECOGNIZED : result;
    }

    public static final int DESTID_FIELD_NUMBER = 6;
    private volatile java.lang.Object destId_;
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    public java.lang.String getDestId() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timeStamp_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 timeStamp = 7;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 8;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
     */
    public com.zzh.protobuf.Msg.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      com.zzh.protobuf.Msg.MsgType result = com.zzh.protobuf.Msg.MsgType.valueOf(msgType_);
      return result == null ? com.zzh.protobuf.Msg.MsgType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (msgId_ != 0L) {
        output.writeInt64(2, msgId_);
      }
      if (fromModule_ != com.zzh.protobuf.Msg.Module.CLIENT.getNumber()) {
        output.writeEnum(3, fromModule_);
      }
      if (!getFromIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromId_);
      }
      if (destModule_ != com.zzh.protobuf.Msg.Module.CLIENT.getNumber()) {
        output.writeEnum(5, destModule_);
      }
      if (!getDestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, destId_);
      }
      if (timeStamp_ != 0L) {
        output.writeInt64(7, timeStamp_);
      }
      if (msgType_ != com.zzh.protobuf.Msg.MsgType.SINGLE.getNumber()) {
        output.writeEnum(8, msgType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, msgId_);
      }
      if (fromModule_ != com.zzh.protobuf.Msg.Module.CLIENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, fromModule_);
      }
      if (!getFromIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromId_);
      }
      if (destModule_ != com.zzh.protobuf.Msg.Module.CLIENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, destModule_);
      }
      if (!getDestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, destId_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timeStamp_);
      }
      if (msgType_ != com.zzh.protobuf.Msg.MsgType.SINGLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, msgType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzh.protobuf.Msg.Head)) {
        return super.equals(obj);
      }
      com.zzh.protobuf.Msg.Head other = (com.zzh.protobuf.Msg.Head) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (getMsgId()
          != other.getMsgId()) return false;
      if (fromModule_ != other.fromModule_) return false;
      if (!getFromId()
          .equals(other.getFromId())) return false;
      if (destModule_ != other.destModule_) return false;
      if (!getDestId()
          .equals(other.getDestId())) return false;
      if (getTimeStamp()
          != other.getTimeStamp()) return false;
      if (msgType_ != other.msgType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + FROMMODULE_FIELD_NUMBER;
      hash = (53 * hash) + fromModule_;
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
      hash = (37 * hash) + DESTMODULE_FIELD_NUMBER;
      hash = (53 * hash) + destModule_;
      hash = (37 * hash) + DESTID_FIELD_NUMBER;
      hash = (53 * hash) + getDestId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzh.protobuf.Msg.Head parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Head parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Msg.Head parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Msg.Head parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzh.protobuf.Msg.Head prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzh.protobuf.Head}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzh.protobuf.Head)
        com.zzh.protobuf.Msg.HeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Head_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Head_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzh.protobuf.Msg.Head.class, com.zzh.protobuf.Msg.Head.Builder.class);
      }

      // Construct using com.zzh.protobuf.Msg.Head.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        msgId_ = 0L;

        fromModule_ = 0;

        fromId_ = "";

        destModule_ = 0;

        destId_ = "";

        timeStamp_ = 0L;

        msgType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzh.protobuf.Msg.internal_static_com_zzh_protobuf_Head_descriptor;
      }

      @java.lang.Override
      public com.zzh.protobuf.Msg.Head getDefaultInstanceForType() {
        return com.zzh.protobuf.Msg.Head.getDefaultInstance();
      }

      @java.lang.Override
      public com.zzh.protobuf.Msg.Head build() {
        com.zzh.protobuf.Msg.Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zzh.protobuf.Msg.Head buildPartial() {
        com.zzh.protobuf.Msg.Head result = new com.zzh.protobuf.Msg.Head(this);
        result.version_ = version_;
        result.msgId_ = msgId_;
        result.fromModule_ = fromModule_;
        result.fromId_ = fromId_;
        result.destModule_ = destModule_;
        result.destId_ = destId_;
        result.timeStamp_ = timeStamp_;
        result.msgType_ = msgType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzh.protobuf.Msg.Head) {
          return mergeFrom((com.zzh.protobuf.Msg.Head)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzh.protobuf.Msg.Head other) {
        if (other == com.zzh.protobuf.Msg.Head.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.fromModule_ != 0) {
          setFromModuleValue(other.getFromModuleValue());
        }
        if (!other.getFromId().isEmpty()) {
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.destModule_ != 0) {
          setDestModuleValue(other.getDestModuleValue());
        }
        if (!other.getDestId().isEmpty()) {
          destId_ = other.destId_;
          onChanged();
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzh.protobuf.Msg.Head parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzh.protobuf.Msg.Head) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       *消息唯一id
       * </pre>
       *
       * <code>int64 msgId = 2;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息唯一id
       * </pre>
       *
       * <code>int64 msgId = 2;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一id
       * </pre>
       *
       * <code>int64 msgId = 2;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private int fromModule_ = 0;
      /**
       * <pre>
       *发送者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
       */
      public int getFromModuleValue() {
        return fromModule_;
      }
      /**
       * <pre>
       *发送者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
       */
      public Builder setFromModuleValue(int value) {
        fromModule_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
       */
      public com.zzh.protobuf.Msg.Module getFromModule() {
        @SuppressWarnings("deprecation")
        com.zzh.protobuf.Msg.Module result = com.zzh.protobuf.Msg.Module.valueOf(fromModule_);
        return result == null ? com.zzh.protobuf.Msg.Module.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *发送者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
       */
      public Builder setFromModule(com.zzh.protobuf.Msg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fromModule_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 3;</code>
       */
      public Builder clearFromModule() {
        
        fromModule_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fromId_ = "";
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder clearFromId() {
        
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromId_ = value;
        onChanged();
        return this;
      }

      private int destModule_ = 0;
      /**
       * <pre>
       *接收者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 5;</code>
       */
      public int getDestModuleValue() {
        return destModule_;
      }
      /**
       * <pre>
       *接收者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 5;</code>
       */
      public Builder setDestModuleValue(int value) {
        destModule_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 5;</code>
       */
      public com.zzh.protobuf.Msg.Module getDestModule() {
        @SuppressWarnings("deprecation")
        com.zzh.protobuf.Msg.Module result = com.zzh.protobuf.Msg.Module.valueOf(destModule_);
        return result == null ? com.zzh.protobuf.Msg.Module.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *接收者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 5;</code>
       */
      public Builder setDestModule(com.zzh.protobuf.Msg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        destModule_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者module
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 5;</code>
       */
      public Builder clearDestModule() {
        
        destModule_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object destId_ = "";
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public java.lang.String getDestId() {
        java.lang.Object ref = destId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDestIdBytes() {
        java.lang.Object ref = destId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder setDestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder clearDestId() {
        
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder setDestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destId_ = value;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 timeStamp = 7;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 timeStamp = 7;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 timeStamp = 7;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public com.zzh.protobuf.Msg.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        com.zzh.protobuf.Msg.MsgType result = com.zzh.protobuf.Msg.MsgType.valueOf(msgType_);
        return result == null ? com.zzh.protobuf.Msg.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public Builder setMsgType(com.zzh.protobuf.Msg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzh.protobuf.Head)
    }

    // @@protoc_insertion_point(class_scope:com.zzh.protobuf.Head)
    private static final com.zzh.protobuf.Msg.Head DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzh.protobuf.Msg.Head();
    }

    public static com.zzh.protobuf.Msg.Head getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Head>
        PARSER = new com.google.protobuf.AbstractParser<Head>() {
      @java.lang.Override
      public Head parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Head(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Head> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Head> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zzh.protobuf.Msg.Head getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzh_protobuf_Protocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzh_protobuf_Protocol_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzh_protobuf_Head_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzh_protobuf_Head_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\020com.zzh.protobuf\"V\n\010Protoco" +
      "l\022\'\n\007msgHead\030\001 \001(\0132\026.com.zzh.protobuf.He" +
      "ad\022\017\n\007msgBody\030\002 \001(\t\022\020\n\010addition\030\003 \001(\t\"\341\001" +
      "\n\004Head\022\017\n\007version\030\001 \001(\005\022\r\n\005msgId\030\002 \001(\003\022," +
      "\n\nfromModule\030\003 \001(\0162\030.com.zzh.protobuf.Mo" +
      "dule\022\016\n\006fromId\030\004 \001(\t\022,\n\ndestModule\030\005 \001(\016" +
      "2\030.com.zzh.protobuf.Module\022\016\n\006destId\030\006 \001" +
      "(\t\022\021\n\ttimeStamp\030\007 \001(\003\022*\n\007msgType\030\010 \001(\0162\031" +
      ".com.zzh.protobuf.MsgType* \n\006Module\022\n\n\006C" +
      "LIENT\020\000\022\n\n\006SERVER\020\001*W\n\007MsgType\022\n\n\006SINGLE" +
      "\020\000\022\t\n\005GROUP\020\002\022\t\n\005GREET\020\003\022\007\n\003ACK\020\004\022\t\n\005ERR" +
      "OR\020\005\022\t\n\005HEART\020\006\022\013\n\007OFFLINE\020\007B\005B\003Msgb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zzh_protobuf_Protocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zzh_protobuf_Protocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzh_protobuf_Protocol_descriptor,
        new java.lang.String[] { "MsgHead", "MsgBody", "Addition", });
    internal_static_com_zzh_protobuf_Head_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zzh_protobuf_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzh_protobuf_Head_descriptor,
        new java.lang.String[] { "Version", "MsgId", "FromModule", "FromId", "DestModule", "DestId", "TimeStamp", "MsgType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
