// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.zzh.protobuf;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.zzh.protobuf.Module}
   */
  public enum Module
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLIENT = 0;</code>
     */
    CLIENT(0),
    /**
     * <code>SERVER = 1;</code>
     */
    SERVER(1),
    /**
     * <code>TRANSFER = 2;</code>
     */
    TRANSFER(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLIENT = 0;</code>
     */
    public static final int CLIENT_VALUE = 0;
    /**
     * <code>SERVER = 1;</code>
     */
    public static final int SERVER_VALUE = 1;
    /**
     * <code>TRANSFER = 2;</code>
     */
    public static final int TRANSFER_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Module valueOf(int value) {
      return forNumber(value);
    }

    public static Module forNumber(int value) {
      switch (value) {
        case 0: return CLIENT;
        case 1: return SERVER;
        case 2: return TRANSFER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Module>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Module> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Module>() {
            public Module findValueByNumber(int number) {
              return Module.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zzh.protobuf.Protocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final Module[] VALUES = values();

    public static Module valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Module(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zzh.protobuf.Module)
  }

  /**
   * Protobuf enum {@code com.zzh.protobuf.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *私聊消息
     * </pre>
     *
     * <code>SINGLE = 0;</code>
     */
    SINGLE(0),
    /**
     * <pre>
     *群聊消息
     * </pre>
     *
     * <code>GROUP = 2;</code>
     */
    GROUP(2),
    /**
     * <pre>
     *登录问候
     * </pre>
     *
     * <code>GREET = 3;</code>
     */
    GREET(3),
    /**
     * <pre>
     *ack
     * </pre>
     *
     * <code>ACK = 4;</code>
     */
    ACK(4),
    /**
     * <pre>
     *错误
     * </pre>
     *
     * <code>ERROR = 5;</code>
     */
    ERROR(5),
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HEART = 6;</code>
     */
    HEART(6),
    /**
     * <pre>
     *下线
     * </pre>
     *
     * <code>OFFLINE = 7;</code>
     */
    OFFLINE(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *私聊消息
     * </pre>
     *
     * <code>SINGLE = 0;</code>
     */
    public static final int SINGLE_VALUE = 0;
    /**
     * <pre>
     *群聊消息
     * </pre>
     *
     * <code>GROUP = 2;</code>
     */
    public static final int GROUP_VALUE = 2;
    /**
     * <pre>
     *登录问候
     * </pre>
     *
     * <code>GREET = 3;</code>
     */
    public static final int GREET_VALUE = 3;
    /**
     * <pre>
     *ack
     * </pre>
     *
     * <code>ACK = 4;</code>
     */
    public static final int ACK_VALUE = 4;
    /**
     * <pre>
     *错误
     * </pre>
     *
     * <code>ERROR = 5;</code>
     */
    public static final int ERROR_VALUE = 5;
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HEART = 6;</code>
     */
    public static final int HEART_VALUE = 6;
    /**
     * <pre>
     *下线
     * </pre>
     *
     * <code>OFFLINE = 7;</code>
     */
    public static final int OFFLINE_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return SINGLE;
        case 2: return GROUP;
        case 3: return GREET;
        case 4: return ACK;
        case 5: return ERROR;
        case 6: return HEART;
        case 7: return OFFLINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zzh.protobuf.Protocol.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zzh.protobuf.MsgType)
  }

  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zzh.protobuf.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息唯一id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     *消息唯一id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>string timeStamp = 2;</code>
     */
    java.lang.String getTimeStamp();
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>string timeStamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string sessionId = 3;</code>
     */
    java.lang.String getSessionId();
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string sessionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    java.lang.String getFromId();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
     */
    int getFromModuleValue();
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
     */
    com.zzh.protobuf.Protocol.Module getFromModule();

    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    java.lang.String getDestId();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    com.google.protobuf.ByteString
        getDestIdBytes();

    /**
     * <pre>
     *接收者模块
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module destModule = 7;</code>
     */
    int getDestModuleValue();
    /**
     * <pre>
     *接收者模块
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module destModule = 7;</code>
     */
    com.zzh.protobuf.Protocol.Module getDestModule();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
     */
    int getMsgTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
     */
    com.zzh.protobuf.Protocol.MsgType getMsgType();

    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    java.lang.String getMsgBody();
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    com.google.protobuf.ByteString
        getMsgBodyBytes();

    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string addition = 10;</code>
     */
    java.lang.String getAddition();
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string addition = 10;</code>
     */
    com.google.protobuf.ByteString
        getAdditionBytes();
  }
  /**
   * Protobuf type {@code com.zzh.protobuf.Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zzh.protobuf.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      id_ = "";
      timeStamp_ = "";
      sessionId_ = "";
      fromId_ = "";
      fromModule_ = 0;
      destId_ = "";
      destModule_ = 0;
      msgType_ = 0;
      msgBody_ = "";
      addition_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timeStamp_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fromId_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              fromModule_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              destId_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              destModule_ = rawValue;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              msgBody_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              addition_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zzh.protobuf.Protocol.internal_static_com_zzh_protobuf_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zzh.protobuf.Protocol.internal_static_com_zzh_protobuf_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zzh.protobuf.Protocol.Msg.class, com.zzh.protobuf.Protocol.Msg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     *消息唯一id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息唯一id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timeStamp_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>string timeStamp = 2;</code>
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>string timeStamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private volatile java.lang.Object sessionId_;
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string sessionId = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMID_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromId_;
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMMODULE_FIELD_NUMBER = 5;
    private int fromModule_;
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
     */
    public int getFromModuleValue() {
      return fromModule_;
    }
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
     */
    public com.zzh.protobuf.Protocol.Module getFromModule() {
      @SuppressWarnings("deprecation")
      com.zzh.protobuf.Protocol.Module result = com.zzh.protobuf.Protocol.Module.valueOf(fromModule_);
      return result == null ? com.zzh.protobuf.Protocol.Module.UNRECOGNIZED : result;
    }

    public static final int DESTID_FIELD_NUMBER = 6;
    private volatile java.lang.Object destId_;
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    public java.lang.String getDestId() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTMODULE_FIELD_NUMBER = 7;
    private int destModule_;
    /**
     * <pre>
     *接收者模块
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module destModule = 7;</code>
     */
    public int getDestModuleValue() {
      return destModule_;
    }
    /**
     * <pre>
     *接收者模块
     * </pre>
     *
     * <code>.com.zzh.protobuf.Module destModule = 7;</code>
     */
    public com.zzh.protobuf.Protocol.Module getDestModule() {
      @SuppressWarnings("deprecation")
      com.zzh.protobuf.Protocol.Module result = com.zzh.protobuf.Protocol.Module.valueOf(destModule_);
      return result == null ? com.zzh.protobuf.Protocol.Module.UNRECOGNIZED : result;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 8;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
     */
    public com.zzh.protobuf.Protocol.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      com.zzh.protobuf.Protocol.MsgType result = com.zzh.protobuf.Protocol.MsgType.valueOf(msgType_);
      return result == null ? com.zzh.protobuf.Protocol.MsgType.UNRECOGNIZED : result;
    }

    public static final int MSGBODY_FIELD_NUMBER = 9;
    private volatile java.lang.Object msgBody_;
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    public java.lang.String getMsgBody() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgBody_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDITION_FIELD_NUMBER = 10;
    private volatile java.lang.Object addition_;
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string addition = 10;</code>
     */
    public java.lang.String getAddition() {
      java.lang.Object ref = addition_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addition_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string addition = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAdditionBytes() {
      java.lang.Object ref = addition_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeStamp_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionId_);
      }
      if (!getFromIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromId_);
      }
      if (fromModule_ != com.zzh.protobuf.Protocol.Module.CLIENT.getNumber()) {
        output.writeEnum(5, fromModule_);
      }
      if (!getDestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, destId_);
      }
      if (destModule_ != com.zzh.protobuf.Protocol.Module.CLIENT.getNumber()) {
        output.writeEnum(7, destModule_);
      }
      if (msgType_ != com.zzh.protobuf.Protocol.MsgType.SINGLE.getNumber()) {
        output.writeEnum(8, msgType_);
      }
      if (!getMsgBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, msgBody_);
      }
      if (!getAdditionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, addition_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeStamp_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionId_);
      }
      if (!getFromIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromId_);
      }
      if (fromModule_ != com.zzh.protobuf.Protocol.Module.CLIENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, fromModule_);
      }
      if (!getDestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, destId_);
      }
      if (destModule_ != com.zzh.protobuf.Protocol.Module.CLIENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, destModule_);
      }
      if (msgType_ != com.zzh.protobuf.Protocol.MsgType.SINGLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, msgType_);
      }
      if (!getMsgBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, msgBody_);
      }
      if (!getAdditionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, addition_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zzh.protobuf.Protocol.Msg)) {
        return super.equals(obj);
      }
      com.zzh.protobuf.Protocol.Msg other = (com.zzh.protobuf.Protocol.Msg) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (!getFromId()
          .equals(other.getFromId())) return false;
      if (fromModule_ != other.fromModule_) return false;
      if (!getDestId()
          .equals(other.getDestId())) return false;
      if (destModule_ != other.destModule_) return false;
      if (msgType_ != other.msgType_) return false;
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
      if (!getAddition()
          .equals(other.getAddition())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
      hash = (37 * hash) + FROMMODULE_FIELD_NUMBER;
      hash = (53 * hash) + fromModule_;
      hash = (37 * hash) + DESTID_FIELD_NUMBER;
      hash = (53 * hash) + getDestId().hashCode();
      hash = (37 * hash) + DESTMODULE_FIELD_NUMBER;
      hash = (53 * hash) + destModule_;
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      hash = (37 * hash) + ADDITION_FIELD_NUMBER;
      hash = (53 * hash) + getAddition().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zzh.protobuf.Protocol.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protobuf.Protocol.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Protocol.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zzh.protobuf.Protocol.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zzh.protobuf.Protocol.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zzh.protobuf.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zzh.protobuf.Msg)
        com.zzh.protobuf.Protocol.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zzh.protobuf.Protocol.internal_static_com_zzh_protobuf_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zzh.protobuf.Protocol.internal_static_com_zzh_protobuf_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zzh.protobuf.Protocol.Msg.class, com.zzh.protobuf.Protocol.Msg.Builder.class);
      }

      // Construct using com.zzh.protobuf.Protocol.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        timeStamp_ = "";

        sessionId_ = "";

        fromId_ = "";

        fromModule_ = 0;

        destId_ = "";

        destModule_ = 0;

        msgType_ = 0;

        msgBody_ = "";

        addition_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zzh.protobuf.Protocol.internal_static_com_zzh_protobuf_Msg_descriptor;
      }

      @java.lang.Override
      public com.zzh.protobuf.Protocol.Msg getDefaultInstanceForType() {
        return com.zzh.protobuf.Protocol.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zzh.protobuf.Protocol.Msg build() {
        com.zzh.protobuf.Protocol.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zzh.protobuf.Protocol.Msg buildPartial() {
        com.zzh.protobuf.Protocol.Msg result = new com.zzh.protobuf.Protocol.Msg(this);
        result.id_ = id_;
        result.timeStamp_ = timeStamp_;
        result.sessionId_ = sessionId_;
        result.fromId_ = fromId_;
        result.fromModule_ = fromModule_;
        result.destId_ = destId_;
        result.destModule_ = destModule_;
        result.msgType_ = msgType_;
        result.msgBody_ = msgBody_;
        result.addition_ = addition_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zzh.protobuf.Protocol.Msg) {
          return mergeFrom((com.zzh.protobuf.Protocol.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zzh.protobuf.Protocol.Msg other) {
        if (other == com.zzh.protobuf.Protocol.Msg.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getTimeStamp().isEmpty()) {
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (!other.getFromId().isEmpty()) {
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.fromModule_ != 0) {
          setFromModuleValue(other.getFromModuleValue());
        }
        if (!other.getDestId().isEmpty()) {
          destId_ = other.destId_;
          onChanged();
        }
        if (other.destModule_ != 0) {
          setDestModuleValue(other.getDestModuleValue());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (!other.getMsgBody().isEmpty()) {
          msgBody_ = other.msgBody_;
          onChanged();
        }
        if (!other.getAddition().isEmpty()) {
          addition_ = other.addition_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zzh.protobuf.Protocol.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zzh.protobuf.Protocol.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       *消息唯一id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息唯一id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息唯一id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timeStamp_ = "";
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeStamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>string timeStamp = 2;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionId = 3;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionId = 3;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionId = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromId_ = "";
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder clearFromId() {
        
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromId = 4;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromId_ = value;
        onChanged();
        return this;
      }

      private int fromModule_ = 0;
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
       */
      public int getFromModuleValue() {
        return fromModule_;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
       */
      public Builder setFromModuleValue(int value) {
        fromModule_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
       */
      public com.zzh.protobuf.Protocol.Module getFromModule() {
        @SuppressWarnings("deprecation")
        com.zzh.protobuf.Protocol.Module result = com.zzh.protobuf.Protocol.Module.valueOf(fromModule_);
        return result == null ? com.zzh.protobuf.Protocol.Module.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
       */
      public Builder setFromModule(com.zzh.protobuf.Protocol.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fromModule_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module fromModule = 5;</code>
       */
      public Builder clearFromModule() {
        
        fromModule_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object destId_ = "";
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public java.lang.String getDestId() {
        java.lang.Object ref = destId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDestIdBytes() {
        java.lang.Object ref = destId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder setDestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder clearDestId() {
        
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destId = 6;</code>
       */
      public Builder setDestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destId_ = value;
        onChanged();
        return this;
      }

      private int destModule_ = 0;
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 7;</code>
       */
      public int getDestModuleValue() {
        return destModule_;
      }
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 7;</code>
       */
      public Builder setDestModuleValue(int value) {
        destModule_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 7;</code>
       */
      public com.zzh.protobuf.Protocol.Module getDestModule() {
        @SuppressWarnings("deprecation")
        com.zzh.protobuf.Protocol.Module result = com.zzh.protobuf.Protocol.Module.valueOf(destModule_);
        return result == null ? com.zzh.protobuf.Protocol.Module.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 7;</code>
       */
      public Builder setDestModule(com.zzh.protobuf.Protocol.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        destModule_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者模块
       * </pre>
       *
       * <code>.com.zzh.protobuf.Module destModule = 7;</code>
       */
      public Builder clearDestModule() {
        
        destModule_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public com.zzh.protobuf.Protocol.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        com.zzh.protobuf.Protocol.MsgType result = com.zzh.protobuf.Protocol.MsgType.valueOf(msgType_);
        return result == null ? com.zzh.protobuf.Protocol.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public Builder setMsgType(com.zzh.protobuf.Protocol.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.zzh.protobuf.MsgType msgType = 8;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgBody_ = "";
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 9;</code>
       */
      public java.lang.String getMsgBody() {
        java.lang.Object ref = msgBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBodyBytes() {
        java.lang.Object ref = msgBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 9;</code>
       */
      public Builder setMsgBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 9;</code>
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 9;</code>
       */
      public Builder setMsgBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgBody_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object addition_ = "";
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 10;</code>
       */
      public java.lang.String getAddition() {
        java.lang.Object ref = addition_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addition_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 10;</code>
       */
      public com.google.protobuf.ByteString
          getAdditionBytes() {
        java.lang.Object ref = addition_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addition_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 10;</code>
       */
      public Builder setAddition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addition_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 10;</code>
       */
      public Builder clearAddition() {
        
        addition_ = getDefaultInstance().getAddition();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *扩展字段
       * </pre>
       *
       * <code>string addition = 10;</code>
       */
      public Builder setAdditionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addition_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zzh.protobuf.Msg)
    }

    // @@protoc_insertion_point(class_scope:com.zzh.protobuf.Msg)
    private static final com.zzh.protobuf.Protocol.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zzh.protobuf.Protocol.Msg();
    }

    public static com.zzh.protobuf.Protocol.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zzh.protobuf.Protocol.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zzh_protobuf_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zzh_protobuf_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\020com.zzh.protobuf\"\202\002\n\003Msg\022\n\n" +
      "\002id\030\001 \001(\t\022\021\n\ttimeStamp\030\002 \001(\t\022\021\n\tsessionI" +
      "d\030\003 \001(\t\022\016\n\006fromId\030\004 \001(\t\022,\n\nfromModule\030\005 " +
      "\001(\0162\030.com.zzh.protobuf.Module\022\016\n\006destId\030" +
      "\006 \001(\t\022,\n\ndestModule\030\007 \001(\0162\030.com.zzh.prot" +
      "obuf.Module\022*\n\007msgType\030\010 \001(\0162\031.com.zzh.p" +
      "rotobuf.MsgType\022\017\n\007msgBody\030\t \001(\t\022\020\n\010addi" +
      "tion\030\n \001(\t*.\n\006Module\022\n\n\006CLIENT\020\000\022\n\n\006SERV" +
      "ER\020\001\022\014\n\010TRANSFER\020\002*W\n\007MsgType\022\n\n\006SINGLE\020" +
      "\000\022\t\n\005GROUP\020\002\022\t\n\005GREET\020\003\022\007\n\003ACK\020\004\022\t\n\005ERRO" +
      "R\020\005\022\t\n\005HEART\020\006\022\013\n\007OFFLINE\020\007B\nB\010Protocolb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zzh_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zzh_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zzh_protobuf_Msg_descriptor,
        new java.lang.String[] { "Id", "TimeStamp", "SessionId", "FromId", "FromModule", "DestId", "DestModule", "MsgType", "MsgBody", "Addition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
