# 使用java环境
FROM fabric8/java-alpine-openjdk8-jdk
MAINTAINER zzh<1124212685@qq.com>

#防止中文乱码
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# 缓存目录
VOLUME tmp
# 将当前项目的jar包添加到容器中
ADD "target/route-0.0.1-SNAPSHOT.jar" "Route.jar"
# 当容器启动时 执行启动命令
ENTRYPOINT ["java","-jar","Route.jar"]